### PR TITLE
Fix #23 PW-2747 Improve exception logging

### LINKED ISSUE #23: [PW-2747] Fix empty log rows in the admin panel
**Describe the bug**
In the admin panel some Adyen logs are empty. Shopware thinks it's probably because of formatting issues.

**To Reproduce**
1. Check admin panel and find empty Adyen logs

**Expected behavior**
All logs should be formatted correctly and should show up in the admin panel

### PR DESCRIPTION
**Pull request by runelaenen**
## Summary
Logs should not contain any newlines. Some logger->log() calls are updated to minimize the change of having newlines.

**Fixed issue**:  #23 PW-2747

### CODE REVIEW

File: Components/Adyen/PaymentMethodService.php [hunk 1]
```diff
@@ -88,7 +88,14 @@ public function getPaymentMethods(
         try {
             $paymentMethods = $checkout->paymentMethods($requestParams);
         } catch (AdyenException $e) {
-            $this->logger->critical($e);
+            $this->logger->critical('Adyen Exception', [
+				'message' => $e->getMessage(),
+            	'file' => $e->getFile(),
+				'line' => $e->getLine(),
+				'statuc' => $e->getStatus(),
```
Comment (acampos1916) [inline Components/Adyen/PaymentMethodService.php:95]:
```suggestion
```
