### PR TITLE
[PW-4224] Copying order detail attributes to basket detail on failed payment

### LINKED ISSUE #140: Basket is not completely restored after a failed payment attempt
**Describe the bug**
Some modifications on items in the basket are not restored after a failed payment attempt due to those modifications being marked as `MODE_SURCHARGE_DISCOUNT` and the this type is skipped when restoring the basket [here on line 178](https://github.com/Adyen/adyen-shopware5/blob/43fcedcef3d9c1f418c157d6aafa03a762db6f29/Components/BasketService.php#L178)

### PR DESCRIPTION
**Pull request by acampos1916**
## Summary
On order save and payment failure the plugin will add to the basket the articles that are found in the previous order. But the attributes of those order details were not being added to the basket. Here a function is being added to copy the attribute values from the order detail to the basket.

Some articles might not exist in Shopware and those are added manually to the basket.

## Tested scenarios
Payment failed restores the basket with the order articles + attributes.

**Fixed issue**: 
PW-4224
fixes #140

### CODE REVIEW

**Comment by acampos1916** [comment]
@bortefi could we please get your feedback for this function? We discussed this being an issue for merchants using order detail attributes.

**Review by cyattilakiss — APPROVED** [review]
Nice and clean PR! +1

File: Components/BasketService.php [hunk 1]
```diff
@@ -194,10 +201,58 @@ private function processOrderDetail(Order $order, Detail $orderDetail)
...
+    }
+
+    /**
+     * Copies attributes from the supplied order detail article ID to a basket detail ID
+     *
+     * @param $basketDetailId
+     * @param $orderDetailId
+     * @throws \Zend_Db_Adapter_Exception
+     */
+    private function copyDetailAttributes($orderDetailId, $basketDetailId)
```
Comment (bortefi) [inline Components/BasketService.php:219]: Code looks good.

A few possible improvements:
* copyDetailAttributes could be a individual service, which is then injected in the BasketManager
* adding some type's on $orderDetailId, $basketDetailId would aid as well,  
Shopware 5 tends to use string and int for ids.
* Maybe add an early void return if there are not attributes  
```
$orderDetailAttributes = $orderDetailAttributesResult[0];
if (!count($orderDetailAttributes[0])){
     return;
}
```

**Review by msilvagarcia — CHANGES_REQUESTED** [review]
@bortefi 's comments are great and would be great to implement. Hit me up, I would love to help in that. :)

**Comment by acampos1916** [comment]
@msilvagarcia yep, could you help with those improvements? Indeed those sound like good ideas.

**Comment by bortefi** [comment]
@acampos1916, @msilvagarcia 

I was thinking to refactor it along the lines off:
* split into multiple classes by functionality
* using DI to simplify the complexer logic of restoring a basket from an order 
* split up classes are also easier to test with unit / integration tests
* _note_: BasketService on it's own could use a huge refactor as this is named to become a *fat* service  
(but not needed for now I would say)

## BasketService

```php
 /**
     * @param Detail $orderDetail
     * @throws \Enlight_Event_Exception
     * @throws \Enlight_Exception
     * @throws \Zend_Db_Adapter_Exception
     */
    private function addArticle(Detail $orderDetail)
    {
        $basketDetailId = $this->sBasket->sAddArticle(
            $orderDetail->getArticleNumber(),
            $orderDetail->getQuantity()
        );

      // this is the line to adjust
      $this->detailAttributesRestorer($basketDetailId, $orderDetail->getId());
    }
```

## AdyenPayment/Basket/Restore/DetailAttributeRestorer

```php
namespace AdyenPayment\Basket\Restore\DetailAttributeRestorer;

class DetailAttributesRestorer implement DetailAttributeRestorerInterface {

  public function restore(string $basketDetailId, string $orderDetailId) // or __invoke()
  {
      $orderDetailAttributes = $this->orderDetailAttributeProvider->fetchByOrderDetailId($orderDetailId);
      
      // early return  if no count in $orderDetailAttributes
      ...

      $attributes = $this->provideFillableAttributeColumns();

      // early return  if no count in $attributes (is this possible to be empty?)
      ...

      // Updating the basket attributes with the order attribute values
      $attributeValues = [];
      foreach ($attributes as $attribute) { // in case of a collection a $collection->reduce (array_reduce) could be used
          if (!empty($orderDetailAttributes[$attribute])) {
              $attributeValues[$attribute] = $orderDetailAttributes[$attribute];
          }
      }

    $this->basketDetailAttributeWriter( $basketDetailId,  $attributeValues);
      
  }

  private function provideFillableAttributeColumns(): array 
  {

    // Getting order attributes columns to possibly fill
      $basketAttributesColumns = $this->modelManager
          ->getClassMetadata('Shopware\Models\Attribute\OrderDetail')
          ->getColumnNames();

    // These columns shouldn't be translated from the order detail to the basket detail
    $columnsToSkip = [
        'id',
        'detailID'
    ];

    return array_diff($basketAttributesColumns, $columnsToSkip);
  }
}
```

## AdyenPayment/Dbal/Provider/OrderDetailAttributeProvider (works as a repository for fetching specific data)

```php
namespace AdyenPayment\Dbal\Provider\OrderDetailAttributeProvider;

class OrderDetailAttributeProvider implements OrderDetailAttributeProviderInterface
{
  public function __construct(..)
  {
    $this->db = ..;
  }

   public function fetchByOrderDetailId(string $orderDetailId): array // a collection as return type would be better though 
   {
     $orderDetailAttributesResult = $this->db
            ->select()
            ->from('s_order_details_attributes') // could bge placed in a class constant ORDER_DETAILS_ATTRIBUTES_TABLE
            ->where('detailID=?', $orderDetailId)
            ->query()
            ->fetchAll();

      return $orderDetailAttributesResult[0] ?? []; // to make sure we always have an array as return type
   }
}
```

## AdyenPayment/Dbal/Writer/BasketDetailAttributeWriter (works as a repository or Manager for writing basket data)

```php
namespace AdyenPayment\Dbal\Writer\BasketDetailAttributeWriter;   // Could also be called persister: Persister\BasketDetailAttributePersister

class OrderDetailAttributeWriter implements OrderDetailAttributeProviderInterface
{
  public function __construct(..)
  {
    $this->db = ..;
  }

   public function write / update(string $basketDetailId; array $attributeValues): int // a collection as $attributeValues parameter would be better though
   {
      if (!count($attributeValues)) {
        return 0;
      }

     return $this->db->update( 
                's_order_basket_attributes', // could bge placed in a class constant ORDER_BASKET_ATTRIBUTES_TABLE
                $attributeValues,
                ['basketID = ?' => $basketDetailId]
            );
        
   }
}
```

**Review by msilvagarcia — APPROVED** [review]

**Comment by acampos1916** [comment]
@bortefi @msilvagarcia thanks for the suggestions and refactor, looks great!

**Review by peterojo — APPROVED** [review]
